#!/bin/bash

# Debian Build script for Games.DAWN/wikiLYNX (https://github.com/flamboyantpenguin/wikilynx)

# Prepare source
mkdir wikilynx-$ver
mv debian wikilynx-$ver
cd wikilynx-$ver

wget https://github.com/flamboyantpenguin/wikilynx/archive/refs/heads/master.tar.gz
tar xavf master.tar.gz
mv debian wikilynx-master/wikiLYNX
cd wikilynx-master/wikiLYNX

# Build
dpkg-buildpackage -us -uc

# Copy output
cp ../wikilynx_${version}_$(dpkg --print-architecture).deb /opt/output