#! /usr/bin/env bash


# make sure errors in sourced scripts will cause this script to stop
set -e

export QTWEBENGINE_CHROMIUM_FLAGS="--disable-seccomp-filter-sandbox"

this_dir="$(readlink -f "$(dirname "$0")")"

source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-gstreamer.sh"
source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-qt-hook.sh"

exec "$this_dir"/wikilynx
