FROM debian:12

RUN apt update && apt upgrade -y
RUN apt install libgl1-mesa-dev qt6-webengine-dev cmake wget fuse libfuse2 zip g++ qt6-wayland-dev qt6-multimedia-dev qt6-svg-dev breeze-dev file -y
#RUN modprobe fuse
RUN groupadd fuse
RUN usermod -a -G fuse root

ADD deploy /root

WORKDIR /root

VOLUME /opt/output

CMD ["bash", "./deploy"]
