#!/bin/bash


# A simple script to automate AppImage building for wikiLYNX Game Browser
# https://github.com/flamboyantpenguin/wikiLYNX


# Project Vars
ver="1.5.5"
ARCH=$(uname -m)

arch=$(dpkg --print-architecture)
if [ $arch =  "i386" ]; then ARCH="i386";arch="i686";export GSTREAMER_PLUGINS_DIR=/usr/lib/i386-linux-gnu/gstreamer-1.0;
elif [ $arch =  "armhf" ]; then ARCH="armhf";
else arch=$ARCH; fi

# Deploy vars
export QMAKE=/usr/bin/qmake
export APPIMAGE_EXTRACT_AND_RUN=1
export DEPLOY_PLATFORM_THEMES=true
export EXTRA_PLATFORM_PLUGINS="libqwayland-generic.so;libqwayland-egl.so;libqxcb.so;libqeglfs.so"
export EXTRA_QT_PLUGINS="waylandcompositor;svg;tls;multimedia;mediaservice;imageformats;audio;styles;position;platforms;iconengines;platformthemes"


# Download Requirements
downloadAppImagers() {
    wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$arch.AppImage
    wget https://github.com/linuxdeploy/linuxdeploy/releases/latest/download/linuxdeploy-$ARCH.AppImage
    wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/latest/download/linuxdeploy-plugin-qt-$ARCH.AppImage
    git clone https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer.git
    wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/latest/download/linuxdeploy-plugin-qt-$ARCH.AppImage
    cp linuxdeploy-plugin-gstreamer/linuxdeploy-plugin-gstreamer.sh .
    chmod u+x *.sh
    chmod u+x *.AppImage
}


# Build and Prepare Project
prepareProject() {

    wget https://github.com/flamboyantpenguin/wikiLYNX/archive/refs/tags/v$ver.zip

    mkdir -p AppDir/usr/{share,bin}
    mkdir -p AppDir/usr/share/{applications,metainfo}
    mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
    APPDIR=$(realpath AppDir)


    unzip v$ver.zip
    cd wikilynx-$ver/wikiLYNX

    # stateChanged was changed to checkStateChanged in Qt 6.7; We use Qt 5.15.2 for building AppImage
    sed -i 's/checkStateChanged/stateChanged/g' welcome.cpp # stateChanged was changed to checkStateChanged in Qt 6.7; We use Qt 5.15.2 for building AppImage
    sed -i 's/checkStateChanged/stateChanged/g' leveleditor.cpp
    sed -i 's/currentIndexChanged/currentTextChanged/g' welcome.cpp # Still no use :/

    cmake -DCMAKE_BUILD_TYPE=MinSizeRel .
    make

    cp wikilynx $APPDIR/usr/bin
    cp ./assets/images/wikiLYNX_logo.svg $APPDIR/usr/share/icons/hicolor/scalable/apps
    cp ../docs/desktop/wikilynx.desktop $APPDIR/usr/share/applications
    cp ../docs/desktop/in.org.dawn.wikilynx.appdata.xml $APPDIR/usr/share/metainfo


    cd $APPDIR/..
    rm -rf wikilynx-$ver

}


# Deploy AppDir
echo $ARCH $arch
apt install kde-style-breeze -y
downloadAppImagers
prepareProject

chmod u+x AppRun
sed -i 's|AI\x02|\x00\x00\x00|' *.AppImage
./linuxdeploy-$ARCH.AppImage --appdir $APPDIR --custom-apprun=$APPDIR/../AppRun --plugin qt --plugin gstreamer

# Fixes
bash -c "rm -rf AppDir/usr/lib/libnss*"
bash -c "cp -r /usr/lib/$ARCH-linux-gnu/libcrypto* AppDir/usr/lib"
bash -c "cp -r /usr/lib/$ARCH-linux-gnu/libssl* AppDir/usr/lib"
bash -c "cp AppRun AppDir/AppRun"

# Make AppImage
./appimagetool-$arch.AppImage AppDir

# Copy to output volume
cp wiki*.AppImage /opt/output

# Cleanup
rm -rf AppDir *.zip *.AppImage
