---
name: Build Edge
"on":
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "CMakeLists.txt"
      - "deploy/**"
      - ".gitea/workflows/build-edge.yaml"
  workflow_dispatch: {}

concurrency:
  group: shared-appimage-build-lane
  cancel-in-progress: false

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target: [amd64, i386, arm64, armhf]
        include:
          - target: amd64
            alt_name: x86_64
          - target: i386
            alt_name: i686
          - target: arm64
            alt_name: aarch64
          - target: armhf
            alt_name: armhf

    container:
      image: code.dawn.org.in/flamboyantpenguin/appimager-wikilynx
      options: --platform linux/${{ matrix.target }}

    name: "Build AppImage on ${{matrix.target}}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          cp source/deploy/appimage/AppRun .
          cp source/deploy/deploy ./deployAppImage

          ./deployAppImage

      - name: Publish to Packages
        run: |
          curl --user ${{vars.maintainer}}:${{secrets.TOKEN}} \
          -X DELETE \
          https://code.dawn.org.in/api/packages/flamboyantpenguin/generic/wikilynx/edge/wikiLYNX-${{matrix.target}}.AppImage

          curl --user ${{vars.maintainer}}:${{secrets.TOKEN}} \
          --upload-file ./output/wikiLYNX-${{matrix.alt_name}}.AppImage \
          https://code.dawn.org.in/api/packages/flamboyantpenguin/generic/wikilynx/edge/wikiLYNX-${{matrix.target}}.AppImage
