#!/bin/bash

# Debian Build script for Games.DAWN/wikiLYNX (https://github.com/flamboyantpenguin/wikilynx)

ver=1.5.0
version=1.5.0-1

# Prepare source
wget --output-document v${ver}.zip "https://github.com/flamboyantpenguin/wikiLYNX/archive/refs/tags/v${ver}.zip"
unzip -o v${ver}.zip
cd wikilynx-${ver}/wikiLYNX
sed 's/::checkStateChanged/::stateChanged/g' -i welcome.cpp
sed 's/::checkStateChanged/::stateChanged/g' -i leveleditor.cpp


# Build
echo "yes" | debuild -us -uc

# Copy output
cp ../wikilynx_${version}_$(dpkg --print-architecture).deb /opt/output
