#!/bin/bash

# Debian Build script for Games.DAWN/wikiLYNX (https://github.com/flamboyantpenguin/wikilynx)

ver=1.5.6
version=1.5.6-1

# Prepare source
wget --output-document v${ver}.zip "https://github.com/flamboyantpenguin/wikiLYNX/archive/refs/tags/v${ver}.zip"
unzip -o v${ver}.zip
cd wikilynx-${ver}/wikiLYNX
sed 's/::checkStateChanged/::stateChanged/g' -i about.cpp
sed 's/::checkStateChanged/::stateChanged/g' -i welcome.cpp
sed 's/::checkStateChanged/::stateChanged/g' -i leveleditor.cpp
sed 's/::checkStateChanged/::stateChanged/g' -i levelmanager.cpp

# Apparently hintingpreference doesn't work in Qt5
sed -i '/hintingpreference/d' ui/*.ui

# Build
echo "yes" | debuild -us -uc

# Copy output
cp ../wikilynx_${version}_$(dpkg --print-architecture).deb /opt/output
