#!/bin/bash

# Run this at project root

set -e

CUR_DIR=$(pwd)
BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

case "$(grep 'VERSION_CODENAME=' /etc/os-release | cut -d= -f2)" in
bullseye) DIST="deb11" ;;
bookworm) DIST="deb12" ;;
*)
	echo "Is this debian?"
	exit 1
	;;
esac

CHANNEL="${1:-}"
if [ "$CHANNEL" != "release" ] && [ "$CHANNEL" != "edge" ]; then
	echo "Usage: $0 <release|edge>"
	exit 1
fi

cp -r "deploy/debian/$DIST/debian" ./debian

if [ "$CHANNEL" = "edge" ]; then
	BASE_VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/^[0-9]\+://; s/-.*//')
	DATE="$(date -u +%Y%m%d)"
	HASH="$(git rev-parse --short HEAD)"
	DEB_REV=$(
		dpkg-parsechangelog --show-field Version 2>/dev/null | awk -F'-' 'NF>1 && $NF ~ /^[0-9]+$/ {print $NF; exit} END {print 1}'
	)
	DEB_VERSION="${BASE_VERSION}+git${DATE}.${HASH}-${DEB_REV}~${DIST}"
	CHANGELOG_MSG="Snapshot build from git."
	dch --newversion "$DEB_VERSION" --distribution "unstable" "$CHANGELOG_MSG"
fi

cp -r ./* $BUILD_DIR
cd "$BUILD_DIR"

# Apparently hintingpreference doesn't work in some versions of Qt6 either
sed '/hintingpreference/d' -i src/ui/forms/*.ui

dpkg-buildpackage -us -uc

mv /tmp/*.deb $CUR_DIR

exit 0