#!/bin/bash

# RPM Build script for Games.DAWN/wikiLYNX (https://github.com/flamboyantpenguin/wikilynx)

# Build
spectool -g -R SPECS/*.spec
rpmbuild -ba SPECS/*.spec

# Copy
mv ~/rpmbuild/SRPMS/*fc41.src.rpm /opt/output
mv ~/rpmbuild/RPMS/$(uname -m)/*fc41.$(uname -m).rpm /opt/output
