FROM debian:11

RUN rm /var/lib/dpkg/info/libc-bin*
RUN apt clean && apt update
RUN apt install libc-bin -y
RUN apt install git build-essential patchelf fuse file libfuse2 wget zip -y
RUN apt install cmake libgl1-mesa-dev qtwayland5 qtwayland5-private-dev qtwayland5-dev-tools qtwebengine5-dev qtmultimedia5-dev libqt5multimedia5-plugins -y
RUN apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good -y

RUN groupadd fuse
RUN usermod -a -G fuse root

ADD AppRun /root
ADD deploy /root

WORKDIR /root

VOLUME /output

CMD ["bash", "./deploy"]
