FROM debian:12

RUN apt clean && apt update
RUN apt install git build-essential patchelf fuse file libfuse2 wget zip npm -y
RUN apt install cmake libgl1-mesa-dev qt6-multimedia-dev qt6-wayland qt6-wayland-dev qt6-wayland-dev-tools qt6-svg-dev qt6-webengine-dev -y
RUN apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good -y

RUN groupadd fuse
RUN usermod -a -G fuse root

WORKDIR /root

VOLUME /output

CMD ["bash"]
