#!/bin/bash

# Debian Build script for Games.DAWN/wikiLYNX (https://github.com/flamboyantpenguin/wikilynx)

# Branch
BRANCH="master"

# Prepare source
mkdir wikilynx-$ver
mv debian wikilynx-$ver
cd wikilynx-$ver

wget https://github.com/flamboyantpenguin/wikilynx/archive/refs/heads/$BRANCH.tar.gz
tar xavf $BRANCH.tar.gz
mv debian wikilynx-$BRANCH/src
cd wikilynx-$BRANCH/src

# Deprecated Function Shenanigans
sed 's/::checkStateChanged/::stateChanged/g' -i ui/*.cpp

# Apparently hintingpreference doesn't work in Qt5
sed -i '/hintingpreference/d' ui/forms/*.ui

# Build
dpkg-buildpackage -us -uc

# Copy output
mv ../wikilynx*$(dpkg --print-architecture).deb /opt/output
